using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using MIConvexHull;
using Sabresaurus;
using Sabresaurus.SabreCSG;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UIElements;
using static VoronoiTest3D;

//[ExecuteInEditMode]
public class VoronoiTest3D : MonoBehaviour
{
    //local bounds volume of cube mesh
    private Bounds object_bounds;
    public int num_of_sites = 10;
    //list of 3d positions of voronoi sites
    public List<Vector3> voronoi_sites = new List<Vector3>();
    //list of voronoi cells within cube bounds
    private List<VoronoiCell> finite_cells;
    //voronoi mesh generated by MIConvexHull
    private VoronoiMesh<VoronoiVertex, VoronoiCell, VoronoiEdge<VoronoiVertex, VoronoiCell>> voronoi_mesh;
    //voronoi vertices created from voronoi_sites
    private List<VoronoiVertex> input_vertices;
    //mapping from the original site positions to their corresponding VoronoiVertex
    private Dictionary<Vector3, VoronoiVertex> site_to_vertex_map;


    [System.Serializable]
    public struct plane_data
    {
        public Vector3 normal;
        public float distance;
    }
    private List<plane_data> object_planes;


    private bool fractured = false;

    /// <summary>
    /// Represents a line segment in 3D: intersection of a face's edge with the clipping plane.
    /// </summary>
    public struct Edge3D
    {
        public Vector3 start;
        public Vector3 end;
        public Edge3D(Vector3 s, Vector3 e)
        {
            start = s;
            end = e;
        }
    }

    void Start()
    {
        MeshFilter mesh_filter = GetComponent<MeshFilter>();
        if (mesh_filter == null)
        {
            Debug.LogWarning("No MeshFilter found on this GameObject!");
            mesh_filter = gameObject.AddComponent<MeshFilter>();
            //return;
        }
        Mesh object_mesh = GetComponent<MeshFilter>().sharedMesh;
        if (object_mesh == null)
        {
            Debug.LogError("No mesh from mesh filter!");
            return;
        }

        MeshCollider mesh_collider = GetComponent<MeshCollider>();
        if (mesh_collider == null)
        {
            Debug.LogWarning("No mesh collider on this game object! Adding one.");
            mesh_collider = gameObject.AddComponent<MeshCollider>();
        }
        mesh_collider.sharedMesh = object_mesh;
        mesh_collider.convex = false; //what the fuck?

        //print number of triangle of mesh
        Debug.Log(Equals(object_mesh.triangles.Length, 0) ? "No triangles in mesh" : "Number of triangles in mesh: " + object_mesh.triangles.Length);

        object_planes = GetPlanesFromMesh(object_mesh);
        Debug.Log("Extracted " + object_planes.Count + " planes from object mesh.");

        //generate sites!
        GenerateVoronoiSites();
        //generate diagram using sites!
        GenerateVoronoiDiagram();
        //map sites to VoronoiVertex
        MapSitesToVertices();
        BuildAllVoronoiCells();
    }

    // Update is called once per frame
    void Update()
    {
        if (!fractured && Input.GetMouseButtonDown(0))
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;
            if (Physics.Raycast(ray, out hit))
            {
                if (hit.transform == transform)
                {
                    Fracture();
                    fractured = true;
                }
            }
        }
    }

    void GenerateVoronoiSites()
    {
        voronoi_sites.Clear();

        MeshFilter mesh_filter = GetComponent<MeshFilter>();
        if (mesh_filter == null)
        {
            Debug.LogError("No MeshFilter found on this GameObject!");
            return;
        }

        Bounds local_bounds = mesh_filter.sharedMesh.bounds;

        //Vector3 scaled_size = Vector3.Scale(local_bounds.size, transform.localScale);
        //cube_bounds = new Bounds(local_bounds.center, scaled_size);

        object_bounds = local_bounds;

        //Vector3 scaled_size = Vector3.Scale(local_bounds.size, transform.localScale);
        //Vector3 scaled_center = Vector3.Scale(local_bounds.center, transform.localScale);
        //cube_bounds = new Bounds(scaled_center, scaled_size);

        //Vector3 size = Vector3.Scale(local_bounds.size, transform.localScale);
        Vector3 min = object_bounds.min; //bottom left back corner coord of cube
        Vector3 max = object_bounds.max; //top front right corner coord of cube

        for (int i = 0; i < num_of_sites; i++)
        {
            float x = UnityEngine.Random.Range(min.x, max.x);
            float y = UnityEngine.Random.Range(min.y, max.y);
            float z = UnityEngine.Random.Range(min.z, max.z);
            voronoi_sites.Add(new Vector3(x, y, z));
        }
    }

    void GenerateVoronoiDiagram()
    {
        //convert Vector3 points in voronoi_sites to VoronoiVertex which is required by MIConvexHull. results in a list of VoronoiVertex objects
        input_vertices = voronoi_sites.Select(p => new VoronoiVertex(p.x, p.y, p.z)).ToList();

        //generate the diagram using MIConvexHull using the provided vertices
        voronoi_mesh = VoronoiMesh.Create<VoronoiVertex, VoronoiCell>(input_vertices);

        //stores cells within the cube bounds
        finite_cells = new List<VoronoiCell>();

        MeshFilter mesh_filter = GetComponent<MeshFilter>();

        //iterates over each cell and computers the circumcenter, if cirumcenter is in bounds add it to finite_cells
        //cirumcenter is the center point of a sphere
        foreach (var cell in voronoi_mesh.Vertices)
        {
            cell.ComputeCircumcenter();

            //is cirumcenter in object bounds?! (in this case a cube)

            if (IsPointInsideBounds(cell.Circumcenter, object_bounds))
            {
                finite_cells.Add(cell);
            }
            //if(IsPointInsideMesh(cell.Circumcenter))
            //{
            //finite_cells.Add(cell);
            //}
        }
    }

    void MapSitesToVertices()
    {
        //creates a dictionary mapping from each original site (Vector3) to the corresponding VoronoiVertex.
        //input_vertices correspond directly to voronoi_sites by index, we can do a direct mapping.
        site_to_vertex_map = new Dictionary<Vector3, VoronoiVertex>();
        for (int i = 0; i < voronoi_sites.Count; i++)
        {
            site_to_vertex_map[voronoi_sites[i]] = input_vertices[i];
        }
    }

    void BuildAllVoronoiCells()
    {
        foreach (var site in voronoi_sites)
        {
            BuildVoronoiCellForSite(site);
        }
    }

    void BuildVoronoiCellForSite(Vector3 site_pos)
    {
        if (!site_to_vertex_map.ContainsKey(site_pos))
        {
            return;
        }

        VoronoiVertex site_vertex = site_to_vertex_map[site_pos];

        var cells_with_site = voronoi_mesh.Vertices.Where(v => v.Vertices.Contains(site_vertex)).ToList();

        List<Vector3> circumcenters = new List<Vector3>();
        foreach (var cells in cells_with_site)
        {
            cells.ComputeCircumcenter();
            circumcenters.Add(cells.Circumcenter);
        }

        //create fragment mesh from circumcenters
        Mesh fragment_mesh = CreateMeshFromCircumcenters(circumcenters);

        //convert fragment mesh to polyhedron for clipping
        Polyhedron fragment_polyhedron = MeshToPolyhedron(fragment_mesh);

        //clip polyhedron against object planes
        Polyhedron clipped_polyhedron = ClipPolyhedronAgainstObjectPlanes(fragment_polyhedron, object_planes);

        //convert clipped polyhedron back to mesh
        Mesh clipped_mesh = BuildMeshFromPolyhedron(clipped_polyhedron);
        //and then instantiate as a fragment game object
        CreateFragmentGameObject(clipped_mesh);
    }

    Mesh CreateMeshFromCircumcenters(List<Vector3> points)
    {
        var hull_vertices = points.Select(v => new DefaultVertex { Position = new double[] { v.x, v.y, v.z } }).ToList();
        var hull = ConvexHull.Create(hull_vertices);
        return CreateMeshFromHull(hull.Result);
    }

    Mesh CreateMeshFromHull(ConvexHull<DefaultVertex, DefaultConvexFace<DefaultVertex>> hull)
    {
        var hull_points = hull.Points.ToList();
        Vector3[] mesh_vertices = new Vector3[hull_points.Count];
        Dictionary<Vector3, int> vertex_to_index = new Dictionary<Vector3, int>();

        for (int i = 0; i < hull_points.Count; i++)
        {
            var pos = hull_points[i].Position;
            Vector3 v = new Vector3((float)pos[0], (float)pos[1], (float)pos[2]);
            mesh_vertices[i] = v;
            vertex_to_index[v] = i;
        }

        List<int> triangles = new List<int>();
        foreach (var face in hull.Faces)
        {
            Vector3 va = new Vector3((float)face.Vertices[0].Position[0], (float)face.Vertices[0].Position[1], (float)face.Vertices[0].Position[2]);
            Vector3 vb = new Vector3((float)face.Vertices[1].Position[0], (float)face.Vertices[1].Position[1], (float)face.Vertices[1].Position[2]);
            Vector3 vc = new Vector3((float)face.Vertices[2].Position[0], (float)face.Vertices[2].Position[1], (float)face.Vertices[2].Position[2]);

            int a = vertex_to_index[va];
            int b = vertex_to_index[vb];
            int c = vertex_to_index[vc];

            triangles.Add(a);
            triangles.Add(b);
            triangles.Add(c);
        }

        Mesh mesh = new Mesh();
        mesh.vertices = mesh_vertices;
        mesh.triangles = triangles.ToArray();
        mesh.RecalculateNormals();
        return mesh;
    }

    void CreateFragmentGameObject(Mesh mesh)
    {
        //create a new GameObject to represent the fragment
        GameObject fragment = new GameObject("Fragment");
        fragment.transform.parent = transform;
        fragment.transform.localPosition = Vector3.zero;
        fragment.transform.localRotation = Quaternion.identity;
        fragment.transform.localScale = Vector3.one;

        MeshFilter mesh_filter = fragment.AddComponent<MeshFilter>();
        mesh_filter.mesh = mesh;

        MeshRenderer mesh_renderer = fragment.AddComponent<MeshRenderer>();
        if (GetComponent<MeshRenderer>() != null)
        {
            mesh_renderer.sharedMaterial = GetComponent<MeshRenderer>().sharedMaterial;
        }

        MeshCollider mesh_collider = fragment.AddComponent<MeshCollider>();
        mesh_collider.sharedMesh = mesh;
        mesh_collider.convex = true;

        Rigidbody rigidbody = fragment.AddComponent<Rigidbody>();
        rigidbody.isKinematic = true; //fragments stable until fracture
    }

    void Fracture()
    {
        // Disable the original cube's renderer and collider
        if (GetComponent<Renderer>() != null) GetComponent<Renderer>().enabled = false;
        if (GetComponent<Collider>() != null) GetComponent<Collider>().enabled = false;

        // Activate physics on all fragments
        foreach (Transform fragment in transform)
        {
            Rigidbody rigidbody = fragment.GetComponent<Rigidbody>();
            if (rigidbody != null)
            {
                rigidbody.isKinematic = false;
                rigidbody.AddExplosionForce(50f, transform.position, 1f);
            }
        }
    }

    private void OnDrawGizmos()
    {
        //set Gizmos matrix to the cube's transform, so all gizmos drawn are relative to the cube in world space
        Gizmos.matrix = transform.localToWorldMatrix;

        //draw cube boundaries 
        Gizmos.color = Color.gray;
        Gizmos.DrawWireCube(object_bounds.center, object_bounds.size);

        //draws green spheres at the position of voronoi sites
        Gizmos.color = Color.green;
        foreach (var site in voronoi_sites)
        {
            Gizmos.DrawSphere(site, 0.02f);
        }

        //draw voronoi edges. red lines represent edges of the diagram between finite cells, blue spheres are drawn at circumcenter of finite cells
        //for edges, iterate over each edge in the voronoi mesh. if both source and target cells of edge are within the cube
        //then draw a line between the circumcenters of the source and target cells
        if (voronoi_mesh != null && finite_cells != null)
        {
            Gizmos.color = Color.red;

            foreach (var edge in voronoi_mesh.Edges)
            {
                // Only draw edges between finite cells
                if (finite_cells.Contains(edge.Source) && finite_cells.Contains(edge.Target))
                {
                    Vector3 start = edge.Source.Circumcenter;
                    Vector3 end = edge.Target.Circumcenter;

                    Gizmos.DrawLine(start, end);
                }
            }

            //draw the circumcenters of finite cells (cells in bounds, optional)
            Gizmos.color = Color.blue;
            foreach (var cell in finite_cells)
            {
                Gizmos.DrawSphere(cell.Circumcenter, 0.01f);
            }
        }

        //resets the matrix set at the start of function to not affect other gizmos drawn in the scene (for example 2d test square currently in scene).
        Gizmos.matrix = Matrix4x4.identity;
    }

    List<Polygon> MeshToPolygons(Mesh mesh)
    {
        List<Polygon> polygons = new List<Polygon>();
        Vector3[] verts = mesh.vertices;
        int[] tris = mesh.triangles;

        //each triangle in mesh is turned into 1 polygon
        for (int i = 0; i < tris.Length; i += 3)
        {
            Vector3 a = verts[tris[i]];
            Vector3 b = verts[tris[i + 1]];
            Vector3 c = verts[tris[i + 2]];

            List<Vector3> tri_vertices = new List<Vector3> { a, b, c };

            //convert 3 verts into a polygon
            Polygon polygon = PolygonFactory.ConstructPolygon(tri_vertices, true);

            if (polygon != null)
            {
                polygons.Add(polygon);
            }
            else
            {
                Debug.LogWarning("Failed to create polygon, check MeshToPolygons.");
            }
        }


        return polygons;
    }

    bool IsPointInsideBounds(Vector3 point, Bounds bounds)
    {
        //extend bounds slightly to account for floating point errors in calculating voronoi edges?
        float tolerance = 0.01f;
        Bounds extented_bounds = bounds;
        extented_bounds.Expand(tolerance);

        return extented_bounds.Contains(point);
    }

    private List<plane_data> GetPlanesFromMesh(Mesh mesh)
    {
        List<plane_data> planes = new List<plane_data>();
        Vector3[] verts = mesh.vertices;
        int[] tris = mesh.triangles;
        //set of 3 indices = 1 triangle
        for (int i = 0; i < tris.Length; i += 3)
        {
            Vector3 v0 = verts[tris[i]];
            Vector3 v1 = verts[tris[i + 1]];
            Vector3 v2 = verts[tris[i + 2]];
            //compute normal
            Vector3 normal = Vector3.Cross(v1 - v0, v2 - v0).normalized;
            //compute plane distance
            float distance = -Vector3.Dot(normal, v0);

            planes.Add(new plane_data
            {
                normal = normal,
                distance = distance
            });
        }
        return planes;
    }

    private Polyhedron MeshToPolyhedron(Mesh mesh)
    {
        Polyhedron polyhedron = new Polyhedron();
        Vector3[] verts = mesh.vertices;
        int[] tris = mesh.triangles;

        //one triangle = one Polygon3D
        for (int i = 0; i < tris.Length; i += 3)
        {
            Vector3 v0 = verts[tris[i]];
            Vector3 v1 = verts[tris[i + 1]];
            Vector3 v2 = verts[tris[i + 2]];

            Polygon3D face = new Polygon3D(new List<Vector3> { v0, v1, v2 });
            polyhedron.faces.Add(face);
        }
        return polyhedron;
    }

    /// <summary>
    /// Clips a single 3D polygon (face) against a plane,
    /// returning the clipped polygon and the intersection edges
    /// on that plane.
    /// </summary>
    /// <param name="poly">The polygon to be clipped</param>
    /// <param name="plane_normal">Plane normal</param>
    /// <param name="plane_distance">Distance 'd' in n·x + d=0</param>
    /// <param name="out_edges">Output: intersection line segments on this face's boundary</param>
    private Polygon3D ClipPolygonAgainstPlane(Polygon3D poly, Vector3 plane_normal, float plane_distance, out List<Edge3D> out_edges)
    {
        out_edges = new List<Edge3D>();

        List<Vector3> output_verts = new List<Vector3>();
        int count = poly.vertices.Count;
        //track last intersection point to form segments as the plane can cut multipled edges of the face
        Vector3? previous_intersection = null;


        for (int i = 0; i < count; i++)
        {
            Vector3 current = poly.vertices[i];
            Vector3 next = poly.vertices[(i + 1) % count];

            float current_distance = Vector3.Dot(plane_normal, current) + plane_distance;
            float next_distance = Vector3.Dot(plane_normal, next) + plane_distance;

            bool current_inside = (current_distance <= 0f);
            bool next_inside = (next_distance <= 0f);

            //if current vertex is inside keep it
            if (current_inside)
            {
                output_verts.Add(current);
            }

            //if edge crosses plane get point of intersection
            if (current_inside != next_inside)
            {
                float t = current_distance / (current_distance - next_distance);
                Vector3 intersection = Vector3.Lerp(current, next, t);
                output_verts.Add(intersection);

                //track intrsection edges for capping
                if(!previous_intersection.HasValue)
                {
                    //haven't stored an intersection yet so store it
                    previous_intersection = intersection;
                }
                else
                {
                    //we have a stored intersection, create a segment from previous_intersection to this one
                    Edge3D segment = new Edge3D(previous_intersection.Value, intersection);
                    out_edges.Add(segment);

                    //reset previous_intersection so next intersection forms a new segment
                    previous_intersection = null;
                }
            }
        }

        // If we ended with a single intersection in previous_intersection, 
        // it means there's an odd number of intersections, typically means degenerate or partial plane pass.
        // Usually in a well-formed scenario, plane intersects edges in pairs, producing closed segments.
        // This edge case can be handled here.

        return new Polygon3D(output_verts);
    }

    /// <summary>
    /// Clips a polyhedron against a single plane and collects the intersection edges
    /// so that we can form a new capping polygon to fill holes left in fragments.
    /// </summary>
    /// <param name="polyhedron">Input shape</param>
    /// <param name="plane_normal">Plane normal</param>
    /// <param name="plane_distance">Plane distance in the equation n·x + d=0</param>
    /// <param name="intersection_edges">Output: a list of edges formed by the intersection of each face with the plane.</param>
    /// <returns>The clipped polyhedron (inside the plane)</returns>
    private Polyhedron ClipPolyhedronAgainstPlane(Polyhedron polyhedron, Vector3 plane_normal, float plane_distance, out List<Edge3D> intersection_edges)
    {
        intersection_edges = new List<Edge3D>();
        Polyhedron clipped_polyhedron = new Polyhedron();
        foreach (Polygon3D face in polyhedron.faces)
        {
            //clip face and collect edges from face's intersection
            List<Edge3D> face_edges;
            Polygon3D clipped = ClipPolygonAgainstPlane(face, plane_normal, plane_distance, out face_edges);

            //merge these edges with global intersection edges
            intersection_edges.AddRange(face_edges);

            //if clipped polygon has >=3 vertices it is a valid face
            if (clipped.vertices.Count >= 3)
            {
                clipped_polyhedron.faces.Add(clipped);
            }
        }
        return clipped_polyhedron;
    }

    private Polyhedron ClipPolyhedronAgainstObjectPlanes(Polyhedron fragment_polyhedron, List<plane_data> object_planes)
    {
        Polyhedron current_polyhedron = fragment_polyhedron;
        foreach (plane_data plane in object_planes)
        {
            current_polyhedron = ClipPolyhedronAgainstPlane(current_polyhedron, plane.normal, plane.distance);
            if (current_polyhedron.faces.Count == 0)
            {
                //entire fragment was clipped cause out of bounds
                break;
            }
        }
        return current_polyhedron;
    }

    private Vector3 ComputeFaceNormal(Polygon3D face)
    {
        if (face.vertices.Count < 3)
        {
            return Vector3.zero;
        }
        Vector3 v0 = face.vertices[0];
        Vector3 v1 = face.vertices[1];
        Vector3 v2 = face.vertices[2];
        //cross product of v1-v0 and v2-v0
        Vector3 normal = Vector3.Cross(v1 - v0, v2 - v0).normalized;
        return normal;
    }

    private void SortPolygonVerts(Polygon3D face)
    {
        Vector3 centroid = Vector3.zero;
        foreach (var vec in face.vertices)
        {
            centroid += vec;
        }
        centroid /= face.vertices.Count;

        Vector3 normal = ComputeFaceNormal(face);
        if(normal == Vector3.zero)
        {
            return;
        }

        //project onto a plane, if normal = (0,0,1) then project x,y
        //if normal is arbitrary (not aligned with the standard x, y, or z axes), choose an orthonormal basis
        Vector3 u = Vector3.Cross(normal, Vector3.up);
        if (u.sqrMagnitude < 1e-6f)
            u = Vector3.Cross(normal, Vector3.right);
        u.Normalize();
        Vector3 v = Vector3.Cross(normal, u);

        List<(Vector3 vertex, float angle)> angled_verts = new List<(Vector3 vertex, float angle)>();
        foreach(var vertex in face.vertices)
        {
            Vector3 relative = vertex - centroid;
            //project relative vector onto u,v plane
            float x = Vector3.Dot(relative, u);
            float y = Vector3.Dot(relative, v);

            float angle = Mathf.Atan2(y, x);
            angled_verts.Add((vertex, angle));
        }

        //sort by angle and then update face vertices in this order
        angled_verts.Sort((a, b) => a.angle.CompareTo(b.angle));
        face.vertices = angled_verts.Select(x => x.vertex).ToList();
    }

    private Mesh BuildMeshFromPolyhedron(Polyhedron poly)
    {
        List<Vector3> verts = new List<Vector3>();
        List<int> triangles = new List<int>();
        int index_offset = 0;

        foreach (Polygon3D face in poly.faces)
        {
            if (face.vertices.Count < 3) continue;

            SortPolygonVerts(face);

            /*
            //triangle fan approch for triangulation of convex face for each polygon
            //if still fucked look into ear clipping algorithm
            for (int i = 1; i < face.vertices.Count - 1; i++)
            {
                verts.Add(face.vertices[0]);
                verts.Add(face.vertices[i]);
                verts.Add(face.vertices[i + 1]);

                triangles.Add(index_offset);
                triangles.Add(index_offset + 1);
                triangles.Add(index_offset + 2);
                index_offset += 3;
            }*/

            // 2) Compute face normal
            Vector3 faceNormal = ComputeFaceNormal(face);
            if (faceNormal == Vector3.zero || face.vertices.Count < 3)
                continue;

            // 3) Confirm CCW orientation
            if (!EarClippingTriangulation.IsCCW(face.vertices, faceNormal))
            {
                // Flip to ensure CCW
                face.vertices.Reverse();
            }

            // 4) Ear-clip to get local triangle indices
            List<int> localTriangles = EarClippingTriangulation.Triangulate(face.vertices, faceNormal);
            if (localTriangles.Count < 3)
            {
                // Possibly we couldn't triangulate this polygon
                continue;
            }

            // 5) Add the face's vertices to finalVerts
            int baseIndex = verts.Count;
            verts.AddRange(face.vertices);

            // 6) Add each of ear clipping's triangle indices offset by baseIndex
            for (int i = 0; i < localTriangles.Count; i++)
            {
                triangles.Add(baseIndex + localTriangles[i]);
            }
        }

        Mesh clipped_mesh = new Mesh();
        clipped_mesh.vertices = verts.ToArray();
        clipped_mesh.triangles = triangles.ToArray();
        clipped_mesh.RecalculateNormals();
        return clipped_mesh;
    }
}